apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonnotif
  labels:
    app: ribbonnotif
spec:
  selector:
    matchLabels:
      app: ribbonnotif
  template:
    metadata:
      labels:
        app: ribbonnotif
    spec:
      containers:
      - name: ribbonnotif-app
        image: $IMAGE
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 150m
        env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: notif
                  key: api_key
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: ribbonnotif
  labels:
    app: ribbonnotif
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: 'http-ingress'
  selector:
    app: ribbonnotif
