spring:
  application:
    name: ribbon-notif
  graphql:
    graphiql:
      enabled: true

server:
  port : 8081

elasticmail:
  url: https://api.elasticemail.com
  path: /v2/email/send

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    probes:
      enabled: true
